Fix/#182 UI screen 제거
TwoInterval/MacC-GoldenRatio pull request #185
Opened 2022-12-01 07:53 UTC by woo0dev

## 작업사항

- UIScreen 제거
- Layout 생성

<br>

## To Reviewers
- Layout.변수이름 과 같은 방식으로 사용하시면 됩니다.
- UIColor는 @Dorodong96 이 수정 예정입니다.

2022-12-01 10:11 UTC, Dorodong96 approved these changes
너무 고생많으셨습니다! 통일성 있고 깔끔해보일 것 같네요!

2022-12-01 14:37 UTC, Dorodong96 requested changes
직접 PR을 빌드해보니, MapView.swift의 `countLabel.font = UIFont.mapLabelFont` 폰트 수정이 필요할 것 같습니다. 확인 부탁드립니다!

2022-12-01 14:37 UTC, Dorodong96 commented on MacC-GoldenRatio/MacC-GoldenRatio/Sources/Model/Layout.swift
> +	// MARK: MyHomeView
p2: 해당 struct에 대해 별도 인스턴스 생성 없이 프로퍼티만을 enum 처럼 사용한다면, private initialzer로 인스턴스 생성을 막는 것도 좋은 방법이라고 합니다!
```suggestion
struct Layout {
        private init() { }
	// MARK: MyHomeView
```

2022-12-02 05:01 UTC, iDrogba approved these changes
다른화면까지 작업해 주셨군요 수고하셨습니다!

2022-12-02 06:05 UTC, woo0dev commented on MacC-GoldenRatio/MacC-GoldenRatio/Sources/Model/Layout.swift
> +	// MARK: MyHomeView
다 반영 했습니다~~ 감사합니다!!

2022-12-02 06:07 UTC, Dorodong96 approved these changes

2022-12-02 06:40 UTC, merged